### ISSUE TITLE
Confirmation of ITU document models

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-itu#2]
Regarding document types and document status.

Confirmed with ITU-T: the current list is comprehensive. 

>  Just a short comment. An annex to a Recommendation makes part of the Recommendation itself. It is not usual to see it published as a separate file (although there are exceptions).

Z.100 however has Annexes F1, F2 and F3 in separate documents. We probably should still support it. Waiting for confirmation.

**Comment by opoudjis** [comment]
Keep this issue assigned to me: I will review UML, and create RNC based on UML, in this ticket.

**Comment by opoudjis** [comment]
ItuGroup is baroque in its detail, and expecting people to actually key all of that in, multiple times, for each project group, is unrealistic. But that's not my problem (apart from the initial annoyance of implementing it.)

**Comment by opoudjis** [comment]
ProvisionalName is a misfeature, if I understand it correctly. Titles are mandatory simply because of how Asciidoctor works (you always put *something* in): if the title is provisional, that does not stop it being the current title. I've added a document attribute for it, but I don't anticipate it being used.

**Comment by opoudjis** [comment]
If I understand citationUri correctly, there is no reason at all for this to be modelled any differently than it already is in relaton, as bibdata/uri: the uri in bibdata is by definition the URI to cite the document by (as is already the case in all the flavours). I am replacing citationUri with uri in the model. If you had something different in mind, you will need to tell me what it is.

**Comment by ronaldtse** [comment]
No, you’re right. Please fix it :-)

**Comment by ronaldtse** [comment]
ItuGroup- thing is they have multiple types of groups and an undetermined hierarchy. A study group can contain workgroups and then other groups. We cannot mode them all, so might as well give them flexibility.

**Comment by ronaldtse** [comment]
ProvisionalName: should be a type of title as you mentioned. No point in making a special element.

**Comment by opoudjis** [comment]
edition is not a date in relaton, it is a container for editions, and it is unacceptable to violate naming conventions of relaton in downstream flavours of Metanorma. bibdata/version/revision-date already provides this information, and that is what ITU bibdata will use.

**Comment by ronaldtse** [comment]
But this risks conflating edition date and revision date.

**Comment by opoudjis** [comment]
It doesn't conflate them here any more than it does in the rest of relaton. The edition date is `bibdata/date[@type = "published"]`; the revision date has been kept away from `bibdata/date`, and included instead in version information. Nothing is broken, and Relaton should not be tinkered with.

All changes in the information model and in this discussion have been made to metanorma-model-itu, metanorma-itu, and the documentation of ITU on metanorma.com. (I can't push the latter yet, because my Pull Request for documentation updates is still open.)

Let me know when this ticket can be closed.

**Comment by ronaldtse** [comment]
Sorry, my mistake for "provisional name": it is a separate field for document identifier (not the title). e.g. https://www.itu.int/itu-t/recommendations/rec.aspx?rec=13074&lang=en the provisional name is `E.RDR-SCBM`, the official identifier (which is given later) is `E.119`.

**Comment by ronaldtse** [comment]
Re: edition date.

@opoudjis For example, https://www.itu.int/itu-t/recommendations/rec.aspx?rec=13074&lang=en

There are the following dates:
* Approval date:  2017-04-07
* Edition: 1
* Edition date: 04/2017 (in months)

We just need to have these modeled properly. If "Edition Date" happens to be a freeform string, I'm fine with that too.

**Comment by opoudjis** [comment]
Provisional name is going to be modelled as a docidentifier of type "ITU-provisional".

**Comment by opoudjis** [comment]
Put on hold while @ronaldtse gets further input on separate document annexes (initial issue); but the workflow really is not set up for publishing document parts as separate documents.

**Comment by ronaldtse** [comment]
> Z.100 however has Annexes F1, F2 and F3 in separate documents. We probably should still support it. Waiting for confirmation.

Confirmed, this particular document will continue this way. However this practice is not used for other documents. In the long term we should support it.

@opoudjis in fact, this is exactly the use case we need for our compliance docs and MPFA docs. This is a well needed case that we should support.

**Comment by opoudjis** [comment]
Then it's an Annex in name only; in practice it's a separate document, and it's only the metadata that indicates it's part of another document (something bibdata/docrelation already encodes).

So it's just a matter of providing appropriate realisations of `bibdata/docrelation[@type = "partof"]`, right?

And that can be kicked down the road, as a separate ticket once you provide an exemplar. It should not hold up this ticket.

**Comment by ronaldtse** [comment]
Yes, for the annex as a document. Please help ticket a more generic issue for this since this applies to more than a specific flavor. 

For the provisional name, it is indeed a separate document identifier. We can just have it as a document attribute like “:itu-provisional-name:”.

**Comment by ronaldtse** [comment]
Regarding ISO 8601, I’m sure you know in 8601-2 we can specify the truncated form of YYYY-MM. It’s just that we don’t have native ruby implementation (which maybe we should consider, since a lot of that came from us).

**Comment by opoudjis** [comment]
This issue has meandered unacceptably. So::

* Generic issue of allowing a document to be part of another document: I can realise this in metanorma-standoc, but the way a part-of document is linked back to the parent document in display is going to be specific to each document. You will need to identify which standards need that rendering; for now, https://github.com/metanorma/metanorma-standoc/issues/58, https://github.com/metanorma/metanorma-itu/issues/7
* `provisional-name` has already been implemented.
* https://github.com/metanorma/isodoc/issues/90 for Year-Month dates.

This ticket is therefore replaced by those new tickets.

**Comment by ronaldtse** [comment]
Thanks for splitting this into more specific issues!
